### ISSUE TITLE
Error while running the application

### ISSUE THREAD

**Issue by saikumarb23** [winston-dsouza/Online-Food-Ordering-System#1]
Hello,

I am getting the below error while running the application. Please help.

C:\Users\Sai\Desktop\Capstone\Food order\Foody\nbproject\jfx-impl.xml:3550: The following error occurred while executing this line:
C:\Users\Sai\Desktop\Capstone\Food order\Foody\nbproject\jfx-impl.xml:3578: The following error occurred while executing this line:
C:\Users\Sai\Desktop\Capstone\Food order\Foody\nbproject\jfx-impl.xml:3597: The following error occurred while executing this line:
C:\Users\Sai\Desktop\Capstone\Food order\Foody\nbproject\jfx-impl.xml:1251: The following error occurred while executing this line:
C:\Users\Sai\Desktop\Capstone\Food order\Foody\nbproject\jfx-impl.xml:1328: Warning: Could not find resource file "C:\Users\Sai\Desktop\Capstone\Food order\Foody\${libs.MySQLDriver.classpath}" to copy.
BUILD FAILED (total time: 1 second)

**Comment by winston-dsouza** [comment]
Run [Foody](https://github.com/winston-dsouza/Online-Food-Ordering-System/tree/master/Foody) folder and [FoodyOrder](https://github.com/winston-dsouza/Online-Food-Ordering-System/tree/master/FoodyOrder) folder separately. Refer [README.md](https://github.com/winston-dsouza/Online-Food-Ordering-System/blob/master/README.md) folder for complete information.
